package exercise

// Catalog is the canonical list of supported exercises.
// This is the source of truth until exercises are persisted in a database.
//
// To add an exercise: append to this slice. IDs are stable, human-readable
// slugs — never renumber or rename them, because workout logs will reference
// them. To remove an exercise, set DeletedAt rather than deleting the entry.
var Catalog = []Exercise{
	{
		ID:           "leg-extension",
		Name:         "Leg Extension",
		Description:  "Seated on a machine, extend the knees against a padded lever to isolate the quadriceps.",
		MuscleGroups: []MuscleGroup{MuscleQuads},
		Equipment:    []Equipment{EquipmentMachine},
	},
	{
		ID:           "machine-lying-leg-curl",
		Name:         "Machine Lying Leg Curl",
		Description:  "Lying face-down on a machine, curl the heels toward the glutes to isolate the hamstrings.",
		MuscleGroups: []MuscleGroup{MuscleHamstrings},
		Equipment:    []Equipment{EquipmentMachine},
	},
	{
		ID:           "barbell-high-bar-back-squat",
		Name:         "Barbell High Bar Back Squat",
		Description:  "Barbell held high on the traps; squat to depth with a more upright torso than the low-bar variant.",
		MuscleGroups: []MuscleGroup{MuscleQuads, MuscleGlutes, MuscleHamstrings, MuscleCore},
		Equipment:    []Equipment{EquipmentBarbell, EquipmentRack},
	},
	{
		ID:           "barbell-calf-raise",
		Name:         "Barbell Calf Raise",
		Description:  "Standing with a barbell across the upper back, raise onto the balls of the feet to target the calves.",
		MuscleGroups: []MuscleGroup{MuscleCalves},
		Equipment:    []Equipment{EquipmentBarbell},
	},
	{
		ID:           "bodyweight-squat",
		Name:         "Bodyweight Squat",
		Description:  "Squat to depth using only bodyweight; foundational movement for lower body mobility and conditioning.",
		MuscleGroups: []MuscleGroup{MuscleQuads, MuscleGlutes, MuscleHamstrings},
		Equipment:    []Equipment{EquipmentNone},
	},
	{
		ID:           "hanging-leg-raise",
		Name:         "Hanging Leg Raise",
		Description:  "Hanging from a pull-up bar, raise the legs to engage the lower abdominals and hip flexors.",
		MuscleGroups: []MuscleGroup{MuscleCore},
		Equipment:    []Equipment{EquipmentPullupBar},
	},
	{
		ID:           "decline-bench-sit-up",
		Name:         "Decline Bench Sit Up",
		Description:  "Anchored on a decline bench, perform sit-ups against gravity to target the abdominals.",
		MuscleGroups: []MuscleGroup{MuscleCore},
		Equipment:    []Equipment{EquipmentDeclineBench},
	},
	{
		ID:           "seated-cable-row",
		Name:         "Seated Cable Row",
		Description:  "Seated at a low-pulley cable station, row the handle to the abdomen to target the mid-back and lats.",
		MuscleGroups: []MuscleGroup{MuscleBack},
		Equipment:    []Equipment{EquipmentCable},
	},
	{
		ID:           "dumbbell-bench-press",
		Name:         "Dumbbell Bench Press",
		Description:  "Lying on a flat bench, press a pair of dumbbells from chest level to lockout to target the chest.",
		MuscleGroups: []MuscleGroup{MuscleChest},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentFlatBench},
	},
	{
		ID:           "barbell-bent-over-row",
		Name:         "Barbell Bent Over Row",
		Description:  "Hinged at the hips with a flat back, row a barbell to the lower chest/upper abdomen to target the mid-back and lats.",
		MuscleGroups: []MuscleGroup{MuscleBack},
		Equipment:    []Equipment{EquipmentBarbell},
	},
	{
		ID:           "incline-dumbbell-bench-press",
		Name:         "Incline Dumbbell Bench Press",
		Description:  "On an incline bench, press a pair of dumbbells from upper-chest level to lockout; the angle shifts load to the upper chest and front delts.",
		MuscleGroups: []MuscleGroup{MuscleChest, MuscleShoulders},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentInclineBench},
	},
	{
		ID:           "incline-dumbbell-fly",
		Name:         "Incline Dumbbell Fly",
		Description:  "On an incline bench with a slight elbow bend, lower dumbbells out in an arc and squeeze them back together to isolate the upper chest.",
		MuscleGroups: []MuscleGroup{MuscleChest},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentInclineBench},
	},
	{
		ID:           "pull-up",
		Name:         "Pull Up",
		Description:  "Hanging from an overhand grip on a pull-up bar, pull the chest toward the bar to target the lats and mid-back.",
		MuscleGroups: []MuscleGroup{MuscleBack},
		Equipment:    []Equipment{EquipmentPullupBar},
	},
	{
		ID:           "hanging-knee-raise",
		Name:         "Hanging Knee Raise",
		Description:  "Hanging from a pull-up bar, raise the knees toward the chest to engage the lower abdominals. Easier regression of the hanging leg raise.",
		MuscleGroups: []MuscleGroup{MuscleCore},
		Equipment:    []Equipment{EquipmentPullupBar},
	},
	{
		ID:           "cable-crunch",
		Name:         "Cable Crunch",
		Description:  "Kneeling at a high-pulley cable station with a rope attachment, crunch the torso toward the floor to target the abdominals under cable tension.",
		MuscleGroups: []MuscleGroup{MuscleCore},
		Equipment:    []Equipment{EquipmentCable},
	},
	{
		ID:           "dumbbell-lateral-raise",
		Name:         "Dumbbell Lateral Raise",
		Description:  "Standing with a dumbbell in each hand, raise the arms out to the sides to shoulder height to isolate the side deltoids.",
		MuscleGroups: []MuscleGroup{MuscleShoulders},
		Equipment:    []Equipment{EquipmentDumbbell},
	},
	{
		ID:           "seated-dumbbell-press",
		Name:         "Seated Dumbbell Press",
		Description:  "Seated against an upright bench, press a pair of dumbbells from shoulder level to overhead lockout to target the front and side deltoids.",
		MuscleGroups: []MuscleGroup{MuscleShoulders},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentUprightBench},
	},
	{
		ID:           "machine-rear-delt-fly",
		Name:         "Machine Rear Delt Fly",
		Description:  "Seated facing the pads of a reverse-pec-deck machine, pull the handles outward in an arc to isolate the rear deltoids.",
		MuscleGroups: []MuscleGroup{MuscleShoulders},
		Equipment:    []Equipment{EquipmentMachine},
	},
	{
		ID:           "seated-dumbbell-bicep-curl",
		Name:         "Seated Dumbbell Bicep Curl",
		Description:  "Seated against an upright bench with a dumbbell in each hand, curl the weight from full extension to full flexion to isolate the biceps; the seated position prevents using the hips to cheat the rep.",
		MuscleGroups: []MuscleGroup{MuscleBiceps},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentUprightBench},
	},
	{
		ID:           "seated-hammer-curl",
		Name:         "Seated Hammer Curl",
		Description:  "Seated against an upright bench with a neutral (palms-facing) grip on the dumbbells, curl through full range; the neutral grip shifts load onto the brachioradialis alongside the biceps.",
		MuscleGroups: []MuscleGroup{MuscleBiceps, MuscleForearms},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentUprightBench},
	},
	{
		ID:           "cable-rope-tricep-extension",
		Name:         "Cable Rope Tricep Extension",
		Description:  "Standing at a high-pulley cable station with a rope attachment, extend the elbows from a flexed position down to full lockout to isolate the triceps.",
		MuscleGroups: []MuscleGroup{MuscleTriceps},
		Equipment:    []Equipment{EquipmentCable},
	},
	{
		ID:           "lying-dumbbell-tricep-extension",
		Name:         "Lying Dumbbell Tricep Extension",
		Description:  "Lying on a flat bench, lower a pair of dumbbells from arms-extended over the chest toward the forehead and press back to lockout; isolates the triceps under stretch.",
		MuscleGroups: []MuscleGroup{MuscleTriceps},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentFlatBench},
	},
	{
		ID:           "reverse-crunch",
		Name:         "Reverse Crunch",
		Description:  "Lying on the floor with hands anchored at the hips or overhead, draw the knees and hips toward the chest by rolling the pelvis up; targets the lower abdominals.",
		MuscleGroups: []MuscleGroup{MuscleCore},
		Equipment:    []Equipment{EquipmentNone},
	},
	{
		ID:           "sit-up",
		Name:         "Sit Up",
		Description:  "Lying on the floor with knees bent and feet planted, curl the torso up to a fully seated position to target the abdominals.",
		MuscleGroups: []MuscleGroup{MuscleCore},
		Equipment:    []Equipment{EquipmentNone},
	},
	{
		ID:           "dumbbell-bulgarian-split-squat",
		Name:         "Dumbbell Bulgarian Split Squat",
		Description:  "Standing in a split stance with the rear foot elevated on a bench and a dumbbell in each hand, descend into a lunge and drive back up through the front foot to target the quads and glutes of the working leg.",
		MuscleGroups: []MuscleGroup{MuscleQuads, MuscleGlutes},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentFlatBench},
	},
	{
		ID:           "barbell-bench-press",
		Name:         "Barbell Bench Press",
		Description:  "Lying on a flat bench, press a barbell from chest level to lockout to target the chest; the foundational horizontal push movement.",
		MuscleGroups: []MuscleGroup{MuscleChest},
		Equipment:    []Equipment{EquipmentBarbell, EquipmentFlatBench},
	},
	{
		ID:           "dumbbell-tripod-row",
		Name:         "Dumbbell Tripod Row",
		Description:  "Bracing one hand against a flat bench in a split stance, row a dumbbell with the opposite hand to the hip; unilateral mid-back work with three points of contact for stability.",
		MuscleGroups: []MuscleGroup{MuscleBack},
		Equipment:    []Equipment{EquipmentDumbbell, EquipmentFlatBench},
	},
	{
		ID:           "machine-fly",
		Name:         "Machine Fly",
		Description:  "Seated on a pec deck with the forearms or hands against the pads, bring the arms together in front of the chest in an arc to isolate the chest.",
		MuscleGroups: []MuscleGroup{MuscleChest},
		Equipment:    []Equipment{EquipmentMachine},
	},
	{
		ID:           "barbell-military-press",
		Name:         "Barbell Military Press",
		Description:  "Standing with the feet close together (military stance), press a barbell from clavicle level to overhead lockout strictly — no leg drive — to target the front and side deltoids.",
		MuscleGroups: []MuscleGroup{MuscleShoulders},
		Equipment:    []Equipment{EquipmentBarbell, EquipmentRack},
	},
	{
		ID:           "standing-barbell-bicep-curl",
		Name:         "Standing Barbell Bicep Curl",
		Description:  "Standing with a barbell held at arm's length, curl the weight from full extension to full flexion to target the biceps.",
		MuscleGroups: []MuscleGroup{MuscleBiceps},
		Equipment:    []Equipment{EquipmentBarbell},
	},
	{
		ID:           "standing-dumbbell-hammer-curl",
		Name:         "Standing Dumbbell Hammer Curl",
		Description:  "Standing with a neutral (palms-facing) grip on the dumbbells, curl through full range; the neutral grip shifts load onto the brachioradialis alongside the biceps.",
		MuscleGroups: []MuscleGroup{MuscleBiceps, MuscleForearms},
		Equipment:    []Equipment{EquipmentDumbbell},
	},
	{
		ID:           "ez-bar-skullcrusher",
		Name:         "EZ Bar Skullcrusher",
		Description:  "Lying on a flat bench with an EZ bar held over the chest, lower the bar toward the forehead by flexing only at the elbows, then extend back to lockout to isolate the triceps; the EZ bar's angled grip reduces wrist strain compared to a straight bar.",
		MuscleGroups: []MuscleGroup{MuscleTriceps},
		Equipment:    []Equipment{EquipmentEZBar, EquipmentFlatBench},
	},
}
